juntagrico_bookkeeping/urls.py
from django.conf.urls import url
from juntagrico_bookkeeping import views as bookkeeping

urlpatterns = [
    url(r'^bk/subscription_bookings$', bookkeeping.subscription_bookings),
    url(r'^bk/bills$', bookkeeping.bills)
]

juntagrico_bookkeeping/models.py
from django.db import models

from juntagrico_bookkeeping.entity.bill import *
from juntagrico_bookkeeping.entity.account import *
from juntagrico_bookkeeping.entity.settings import *

juntagrico_bookkeeping/views.py
import datetime 

from django.http import HttpResponse
from django.shortcuts import render
from django import forms
from django.contrib.auth.decorators import permission_required

from juntagrico_bookkeeping.util.bookings import subscription_bookings_by_date, extrasub_bookings_by_date

from juntagrico.views import get_menu_dict
from juntagrico.models import Subscription
from juntagrico_bookkeeping.models import Bill
from juntagrico.util.temporal import start_of_business_year, start_of_next_business_year
from juntagrico.util.xls import generate_excel

@permission_required('juntagrico.is_book_keeper')
def subscription_bookings(request):
    """
    List of subscriptions
    """
    class DateRangeForm(forms.Form):
        fromdate = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}))
        tilldate = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}))

    default_range = {
        'fromdate': start_of_business_year(),
        'tilldate': start_of_next_business_year() - datetime.timedelta(1)
        }

    if 'fromdate' in request.GET and 'tilldate' in request.GET:
        # request with query parameter
        daterange_form = DateRangeForm(request.GET)    
    else:
        daterange_form = DateRangeForm(default_range)

    if daterange_form.is_valid():
        fromdate = daterange_form.cleaned_data['fromdate']
        tilldate = daterange_form.cleaned_data['tilldate']
        # list of bookings for subscriptions and extra subscriptions
        bookings = subscription_bookings_by_date(fromdate, tilldate)
        bookings.extend(extrasub_bookings_by_date(fromdate, tilldate))
        # sort by date and member
        bookings.sort(key=lambda b: b.docnumber)
    else:
        bookings = []   

    if request.GET.get('format', '') == "xlsx":
        return export_bookings(bookings)
    else:    
        renderdict = get_menu_dict(request)
        renderdict .update({
            'daterange_form': daterange_form,
            'bookings': bookings
        })
        return render(request, "bk/subscription_bookings.html", renderdict)


def export_bookings(bookings):
    
    fields ={
        'date':'Datum',
        'docnumber':'Belegnummer',
        'text':'Text',
        'debit_account':'Soll',
        'credit_account': 'Haben',
        'price':'Betrag',
        'member_account': 'KS1 (Mitglied)'        
    }

    # return generate_excell(fields, bookings)
    return generate_excel(fields.items(), bookings, "buchungen")


@permission_required('juntagrico.is_book_keeper')
def bills(request):
    """
    List of bills per year
    """
    renderdict = get_menu_dict(request)
    if not 'year' in renderdict:
        renderdict['year'] = datetime.date.today().year

    bills_list = Bill.objects.all()
    renderdict['bills_list'] = bills_list

    return render(request, "bk/bills.html", renderdict)

juntagrico_bookkeeping/templates/bk/bills.html
{% extends "bk/list_base.html" %}
{% load i18n %}
{% load config %}
{% block page_title %}
    <h3>
        {% trans "Rechnungen" %}
    </h3>
{% endblock %}
{% block list %}
    <table id="filter-table" class="list table" style="display: table;">
        <thead>
            <tr>
                <th class="filter">
                    Nummer
                </th>
                <th class="filter">
                    {% trans "Member" %}
                </th>
                <th class="filter">
                    Datum
                </th>
                <th class="filter">
                    Text
                </th>
                <th class="filter">
                    Betrag
                </th>
                <th class="filter">
                    Verrechnung
                </th>
                <th class="filter">
                    V-Betrag
                </th>
                <th class="filter">
                    Total
                </th>
                <th class="filter">
                    Bezahlt
                </th>
            </tr>
        </thead>
        <tbody>
            {% for bill in bills_list %}
                <tr>
                    <td>
                        {{ bill.ref_number }}
                    </td>
                    <td>
                        {{ bill.member_name }}
                    </td>
                    <td>
                        {{ bill.bill_date |date:"Y-m-d" }}
                    </td>
                    <td>
                        {{ bill.bill_text }}
                    </td>
                    <td>
                        {{ bill.billable_amount }}
                    </td>
                    <td>
                        {{ bill.offset_kind }}
                    </td>
                    <td>
                        {{ bill.offset_amount }}
                    </td> 
                    <td>
                        {{ bill.total_amount }}
                    </td>  
                    <td>
                        {% if bill.paid %}
                            {{ bill.payment_date |date:"Y-m-d" }}
                        {% endif %}
                    </td>                                      
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

juntagrico_bookkeeping/templates/bk/bookkeeping_admin_menu.html
{% if perms.juntagrico.is_book_keeper %}
<li class="nav-item">
    <a class="nav-link" data-toggle="collapse" href="#bk">Buchhaltung <i class="fas fa-angle-right"></i></a>
    <div class="collapse" id="bk">
    <ul class="nav flex-column admin-menu subadmin-menu">
        <li class="nav-item">
            <a class="nav-link" href="/bk/subscription_bookings">Abo Buchungen</a>
        </li>
    </ul>
    </div>
</li>
{% endif %}

juntagrico_bookkeeping/templates/bk/list_base.html
{% extends "base.html" %}
{% load i18n %}
{% load config %}
{% block body_extra_classes %}wide-layout{% endblock %}
{% block styles %}
    <link href="/static/external/datepicker/datepicker.min.css" rel="stylesheet"/>
{% endblock %}
{% block content %}
    {% config "enable_shares" as enable_shares %}
    {% block management_cmd %}
    {% endblock %}
    <div id="managementlist" class="row">
        <div class="col-md-12">
            {% block list %}
            {% endblock %}
        </div>
    </div>
    <br/>
    <br/>
    <script>
        var email_string = "{% trans "Email senden" %}";
        var send_string = "{% trans "senden" %}";
        var email_single_string = "{% trans "Email an diesen" %}";
        var email_multi_string = "{% trans "Email an diese" %}"
        var member_string = "{% vocabulary "member" %}";
        var members_string = "{% vocabulary "member_pl" %}";
    </script>
{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="/static/external/datatables.min.js">
    </script>
    <script type="text/javascript" src="/static/external/datepicker/datepicker.min.js">
    </script>
    <script type="text/javascript" src="/static/external/require.min.js" data-main="/static/js/initManList.js">
    </script>
    {% block extrascripts %}
    {% endblock %}
{% endblock %}

juntagrico_bookkeeping/templates/bk/subscription_bookings.html
{% extends "base.html" %}
{% load config %}
{% block page_title %}
    <h3>Abos</h3>
{% endblock %}

{% block content %}

    <div>Abo Buchungen nach Periode</div><br/>
    <form method="GET">
        <div class="form-group form-inline">
            <label for="id_fromdate" class="mr-3">Von</label> {{ daterange_form.fromdate }} 
            <label for="id_tilldate" class="ml-4 mr-3">bis</label> {{ daterange_form.tilldate }} 
            <!-- <label for="id_tilldate" class="col-form-label col-md-1">bis</label> <div class="col-md-2">{{ daterange_form.tilldate }} </div> -->
            <button id="btn_submit" type="submit" class="ml-4 btn btn-success">OK</button>
        </div>
        <div class="form-group">
            {% if daterange_form.fromdate.errors %}
                <div class="alert alert-danger">Ungültiges Von Datum</div>
            {% endif %}
            {% if daterange_form.tilldate.errors %}
                <div class="alert alert-danger">Ungültiges Bis Datum</div>
            {% endif %}      
        </div>
        <div class="form-group row">
            <button id="btn_excel" type="submit" name="format" value="xlsx" class="col-md-2 btn btn-success">Excel Export</button>
        </div>
    </form> 
    <br/>
    <table id="filter-table" class="list table" style="display: table; font-size: 14px;">
    	<thead>
	    	<tr>
                <th>Datum</th>
	    		<th>Start</th>
	    		<th>Ende</th>
	    		<th>{% vocabulary "member" %}</th>
	    		<th>Bezeichnung</th>
	    		<th class="text-right">Betrag</th>
	    	</tr>
    	</thead>
    	<tbody> 
	        {% for b in bookings %}
	        <tr>
                <td>{{ b.date | date:'d.m.Y'}}</td>
	        	<td>{{ b.activation_date | date:'d.m.Y' }}</td>
	        	<td>{{ b.deactivation_date | date:'d.m.Y' }}</td>
	        	<td>{{ b.member }}</td>
	        	<td>{{ b.text }}</td>
	        	<td class="text-right">{{ b.price | stringformat:'6.2f' }}</td>
	        </tr>
	        {% endfor %}
	    </tbody>
    </table>
{% endblock %}